### ISSUE TITLE
Template variables do not work in a template rule's labels array

### ISSUE THREAD

**Issue by Matthalp** [clulab/processors#119]
Error:
```
while parsing a flow sequence
 in 'string', line 1, column 10:
      label: [${label}]
             ^
expected ',' or ']', but got FlowMappingStart
 in 'string', line 1, column 12:
      label: [${label}]
```

In master.yml:
```
rules:
  - import: template.yml
    vars:
      label: "ALabel"
```

In template.yml:
```
- name: "some-rule"
  label: [${label}]
  type: token
  pattern: |
   [entity="PERSON"]+
```

Note that the following *does* work (as the brackets are removed):
```
- name: "some-rule"
  label: ${label}
  type: token
  pattern: |
   [entity="PERSON"]+
```

**Comment by Matthalp** [comment]
@myedibleenso Do you recall what's needed to fix this? I believe you said it's a fairly easy one a while back

**Comment by myedibleenso** [comment]
@Matthalp, thanks for opening this issue.  I have to look at the code to be sure, but I think it's just a matter of changing when in the process of parsing the grammar that the substitutions are performed.

**Comment by marcovzla** [comment]
The code for substituting the variables in lists is already in place:
https://github.com/clulab/processors/blob/d2d798d07be23be063fb0c4ccfd5bba6a6d4e926/main/src/main/scala/org/clulab/odin/impl/RuleReader.scala#L94

You can check that this works (note the quotes used inside the list):
```
vars:
  label: ALabel

rules:
  - name: some-rule
    label: ["${label}"]
    type: token
    pattern: |
      [entity=PERSON]+
```

I'm not sure if we can fix this behavior without modifying snakeyaml. It seems that snakeyaml doesn't like the open curly bracket inside the list, so maybe one solution is to add support for variables without the curly brackets: `$label` instead of `${label}`.
