### ISSUE TITLE
Add graph field to dependency rules

### ISSUE THREAD

**Issue by myedibleenso** [clulab/processors#153]
Thinking ahead to the eventual inclusion of SRL graphs and universal dependencies, We ought to have a way of  specifying which graph a rule should be applied to.  

We're currently producing `stanford-basic` dependency parses wherever we are using `stanford-collapsed` dependencies.  There are times where it is necessary to write a rule in terms of `stanford-basic`, instead of `stanford-collapsed` (the default).  For example, currently you can't use a preposition as an event trigger (ex. "due to"), because these nodes are disconnected from the `stanford-collapsed` graph.

## Proposed changes

1. Deprecate `type: dependency` in favor of `type: graph`
2. Add `graph:` as an optional rule field field
3. [Rename `Sentence.dependenciesByType` to `Sentence.graphs`](https://github.com/clulab/processors/blob/93f4e18bd899272aa9f65402241bcbc09292debe/main/src/main/scala/org/clulab/processors/Sentence.scala#L32)

## Example
```yaml
- name: "basic-deps-example"
   # type: dependency should also work this way
   type: graph
   graph: "stanford-basic"
   label: Event
   pattern: |
     trigger = due to
     # the rest of your rule here
```

When applied, the rule would check `Sentence.dependenciesByType` for the value corresponding to `graph` if `graph` is specified.  If the `graph` field is not included in a rule of `type: graph` (or `type: dependency`), the matcher would default to `Sentence.dependencies` (currently this points to "stanford-collapsed").
