### ISSUE TITLE
add confidence score to mentions

### ISSUE THREAD

**Issue by myedibleenso** [clulab/processors#170]
This is a proposal to add a `confidence` attribute to mentions.

```
rules:
  - name: "low-confidence-entity-rule"
    label: Entity
    confidence: 0.5 # pattern is not very reliable
    type: token
    pattern: |
      [word=/^[A-Z]/]+ # words beginning with an upper case letter

  - name: "med-confidence-entity-rule"
    label: Entity
    confidence: 0.75 # a bit more reliable than "low-confidence-rule"
    type: token
    pattern: |
      (?! ^ [!tag=NNP]) # the pattern cannot be preceded by a non proper noun beginning the sentence
      [word=/^[A-Z]/]+ # words beginning with an uppercase letter
```

>[Just think, we’ll be able to tell our grandchildren, "I remember the day President Trump tweeted the nuclear launch codes."](https://twitter.com/ConanOBrien/status/895688756539396096)

Note that if you run this in the visualizer you won't be able to see overlapping matches from both rules unless you change the label in one of the rules (ex. `Entity -> PossibleEntity`).

## Required changes
- Currently, if two rules match the same span with the same label, we discard the latter.  We'll want to either keep the match with the highest confidence, or run the rules sorted by priority and confidence.
- Decide on a default value.
- Pull from `yaml` (similar to change made for inclusion of `graph` keyword).
- Add to `OdinConf`

## Questions
- Should it be a `var` or a `val`?  Since mentions can be nested, a `var` might be easier to propagate changes (consider a case where in a postprocessing step you update the confidence values).
