### ISSUE TITLE
Unable to replicate example from docs

### ISSUE THREAD

**Issue by urigoren** [clulab/processors#338]
I am trying to run a dependency rule, with `java`.

To warmup, I'm using the example from the docs: "Oscar lives in the trash can"

with the following rule

```
  - name: dep_event_mention_out
    label: LivesIn
    priority: 1
    type: dependency
    pattern: |
      trigger = [lemma=live]
      resident:Person = nsubj

```

And unfortunately, the dependency is not recognized.

even if I change `nsubj` to `/.*/`, still no results.
See code:
https://github.com/urigoren/odin_rules

Thank you

**Comment by BeckySharp** [comment]
Hi -- did you already label "Oscar" as a `Person`?  I am guessing that that's the issue, as the EventMention needs to land on a previously found Mention (here, prob a TextBoundMention for "Oscar" labeled as `Person`, which you could do in a couple of ways, by first finding all nouns, or better by using the NER tags from the processor)

**Comment by myedibleenso** [comment]
Hi, @urigoren.  Yes, @BeckySharp identified the issue: [looking at your rules](https://github.com/urigoren/odin_rules/blob/b1fd2a45f3a92cd2355e196837491d4b571240b4/data/sample.yaml), it seems you haven't identified "Oscar" as a `Person`.

To test, simply add a rule like the following:

```yaml
# A toy rule that will map the string "Oscar" to a Person mention.
# Note that this rule must run **before** events reference a Person mention
- name: "oscar-quick-fix"
   label: Person
   priority: 1
   type: token
   pattern: |
     "Oscar" 
```

I think this assumption wasn't stated in the caption of the example you're using in your project, though other examples in the manual are explicit about this (ex. Examples 7 & 10).  I apologize for the confusion.  The manual really is in need of an update.  

Also, you will either need to remove the `priority` line from your two event rules, or push both of those to priority 2, as the entity rule is responsible for producing `Person` mentions and your event rules reference/depend on `Person` mentions.

**Comment by urigoren** [comment]
I'm sorry, but it still doesn't work.

I have tried a lot of variation, and neither of them work.

This is the last version of the rules:
```

rules:
  - name: dep_event_mention_out
    label: LivesIn
    priority: 2
    type: dependency
    pattern: |
      trigger = [lemma=live]
      resident:Noun = [outgoing=/nmod|nsubj|det|dep|case|nmod_in|acl:relcl/]
  - name: dep_event_mention_in
    label: LivesIn
    priority: 2
    type: dependency
    pattern: |
      trigger = [lemma=live]
      resident:Noun = [incoming=/nmod|nsubj|det|dep|case|nmod_in|acl:relcl/]
  - name: "oscar-quick-fix"
    label: Noun
    priority: 1
    type: token
    pattern: |
        "Oscar"
  - name: "np"
    label: Noun
    priority: 1
    type: token
    unit: tag
    pattern: |
      /^N/
```

And I also updated the repo:
https://github.com/urigoren/odin_rules

**Comment by BeckySharp** [comment]
I'm looking into/using your grammar now -- will update when I've poked around

**Comment by BeckySharp** [comment]
ok -- so, for the first rule, to get extractions, I think you want something like this:
```  - name: dep_event_mention_out
    label: LivesIn
    priority: 2
    type: dependency
    pattern: |
      trigger = [lemma=live]
      resident:Noun = >/nmod|nsubj|det|dep|case|nmod_in|acl:relcl/
```
Note that you want to *traverse* the dependencies (_starting from the trigger_), so you use the ">" (traverse outgoing) and "<" (traverse incoming).  Using the `[ ]` notation, as you had it, adds a _constraint_ on the token you're landing on, if that helps.
 
That makes links like this:
![image](https://user-images.githubusercontent.com/5384073/63036652-53069400-be72-11e9-8b35-d02190a5e111.png)

Likely, what you're after is a single "living in" event with multiple arguments, like this:
```  - name: dep_event_mention_out
    label: LivesIn
    priority: 2
    type: dependency
    pattern: |
      trigger = [lemma=live]
      resident:Noun = >/nsubj/
      abode: Noun = >/nmod_in/
```

Which makes links like this:
![image](https://user-images.githubusercontent.com/5384073/63036895-d32cf980-be72-11e9-82aa-386e9aa8e9f4.png)

**Comment by BeckySharp** [comment]
But @urigoren please let us know if (a) it's still not working or (b) you have more questions!

**Comment by urigoren** [comment]
Thank you so much, it worked !

Another quick question if I may,
Is it possible to label the subject of a verb as an entity ?

For example, to label `Oscar` as a person, because it is the subject of the verb `lives` ?
If so, what is the rule ?

**Comment by myedibleenso** [comment]
Glad to hear you have it working now.

>Is it possible to label the subject of a verb as an entity ?

Definitely!  For this, you'll want to use a token pattern.  The following rule checks to see if there is an incoming `nsubj` dependency:

```yaml
- name: "nsubj-as-noun"
  label: Noun
  type: token
  pattern: |
    [incoming=nsubj]
```

Note that the rule above will only match a single token.  To handle subjects that are compound noun, you can modify that rule to include any surrounding nouns by adding a constraint on the POS tag and the `*` quantifier (zero or more):

```yaml  
- name: "nsubj-as-noun-expanded"
  label: Noun
  type: token
  pattern: |
    [tag=/^N/]*
    [incoming=nsubj] 
    [tag=/^N/]*
```

Following that same idea, you can expand what's included in the match using additional token constraints in a single rule or by employing a set of scaffolding rules.
